/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author nanda
 */
public class Dasbor extends javax.swing.JFrame {

    /**
     * Creates new form Dasbor
     */
    
    Color DefaultColor, ClickedColor;
    
    public Dasbor() {
        initComponents();
        DefaultColor = new Color(64,115,158);
        ClickedColor = new Color(53,59,72);
        
        //Set default color to pan on run time
        
        pnHome.setBackground(DefaultColor);
        pnProduksi.setBackground(DefaultColor);
        pnBarang.setBackground(DefaultColor);
        pnKaryawan.setBackground(DefaultColor);
        pnLaporan.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnSide = new javax.swing.JPanel();
        lbl_app = new javax.swing.JLabel();
        pnHome = new javax.swing.JPanel();
        lbl_icnHome = new javax.swing.JLabel();
        lbl_Home = new javax.swing.JLabel();
        pnProduksi = new javax.swing.JPanel();
        lbl_icnProduksi = new javax.swing.JLabel();
        lbl_Produksi = new javax.swing.JLabel();
        pnBarang = new javax.swing.JPanel();
        lbl_icnBarang = new javax.swing.JLabel();
        lbl_Barang = new javax.swing.JLabel();
        pnKaryawan = new javax.swing.JPanel();
        lbl_icnKaryawan = new javax.swing.JLabel();
        lbl_Karyawan = new javax.swing.JLabel();
        pnLaporan = new javax.swing.JPanel();
        lbl_icnLaporan = new javax.swing.JLabel();
        lbl_Laporan = new javax.swing.JLabel();
        pnMain = new javax.swing.JDesktopPane();
        pnUp = new javax.swing.JPanel();
        lbl_appblack = new javax.swing.JLabel();
        lbl_Logo = new javax.swing.JLabel();
        MenuName = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 625));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 552));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnSide.setBackground(new java.awt.Color(64, 115, 158));
        pnSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_app.setBackground(new java.awt.Color(64, 115, 158));
        lbl_app.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_app.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/apps.png"))); // NOI18N
        lbl_app.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_app.setOpaque(true);
        lbl_app.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_appMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_appMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_appMouseExited(evt);
            }
        });
        pnSide.add(lbl_app, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 40, 40));

        pnHome.setBackground(new java.awt.Color(64, 115, 158));
        pnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_icnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/home.png"))); // NOI18N
        pnHome.add(lbl_icnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 40, 30));

        lbl_Home.setBackground(new java.awt.Color(64, 115, 158));
        lbl_Home.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Home.setText("Home");
        lbl_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_HomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_HomeMousePressed(evt);
            }
        });
        pnHome.add(lbl_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 20));

        pnSide.add(pnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 40));

        pnProduksi.setBackground(new java.awt.Color(64, 115, 158));
        pnProduksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icnProduksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_icnProduksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/calculator-money.png"))); // NOI18N
        pnProduksi.add(lbl_icnProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 40, 30));

        lbl_Produksi.setBackground(new java.awt.Color(64, 115, 158));
        lbl_Produksi.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Produksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Produksi.setText("Produksi");
        lbl_Produksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ProduksiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_ProduksiMousePressed(evt);
            }
        });
        pnProduksi.add(lbl_Produksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 20));

        pnSide.add(pnProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 40));

        pnBarang.setBackground(new java.awt.Color(64, 115, 158));
        pnBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icnBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_icnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/van-fast.png"))); // NOI18N
        pnBarang.add(lbl_icnBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 40, 30));

        lbl_Barang.setBackground(new java.awt.Color(64, 115, 158));
        lbl_Barang.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Barang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Barang.setText("Barang");
        lbl_Barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_BarangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_BarangMousePressed(evt);
            }
        });
        pnBarang.add(lbl_Barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 20));

        pnSide.add(pnBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 40));

        pnKaryawan.setBackground(new java.awt.Color(64, 115, 158));
        pnKaryawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icnKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_icnKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/users-alt.png"))); // NOI18N
        pnKaryawan.add(lbl_icnKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 40, 30));

        lbl_Karyawan.setBackground(new java.awt.Color(64, 115, 158));
        lbl_Karyawan.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Karyawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Karyawan.setText("Karyawan");
        lbl_Karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_KaryawanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_KaryawanMousePressed(evt);
            }
        });
        pnKaryawan.add(lbl_Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 20));

        pnSide.add(pnKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 210, 40));

        pnLaporan.setBackground(new java.awt.Color(64, 115, 158));
        pnLaporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_icnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/light-emergency-on.png"))); // NOI18N
        pnLaporan.add(lbl_icnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 40, 30));

        lbl_Laporan.setBackground(new java.awt.Color(64, 115, 158));
        lbl_Laporan.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Laporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Laporan.setText("Laporan");
        lbl_Laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_LaporanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_LaporanMousePressed(evt);
            }
        });
        pnLaporan.add(lbl_Laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 20));

        pnSide.add(pnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 210, 40));

        jPanel1.add(pnSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, -1, 552));

        pnMain.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        jPanel1.add(pnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 73, 790, 625));

        pnUp.setBackground(new java.awt.Color(72, 126, 176));
        pnUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_appblack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_appblack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/apps (1).png"))); // NOI18N
        lbl_appblack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_appblack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_appblackMouseClicked(evt);
            }
        });
        pnUp.add(lbl_appblack, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 83, 40, 40));

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/logo-removebg-preview.png"))); // NOI18N
        lbl_Logo.setText("jLabel2");
        pnUp.add(lbl_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 73, 240, 130));

        MenuName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        MenuName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/user.png"))); // NOI18N
        MenuName.setText(" Hi, Mrs. !");
        pnUp.add(MenuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 210, 70));

        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/rectangle-xmark.png"))); // NOI18N
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });
        pnUp.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, 30));

        jPanel1.add(pnUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int x = 210;
    private void lbl_appMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_appMouseClicked
        if (x == 210){
            pnSide.setSize(210,625);
            Thread th= new Thread()
                    {@Override
                        public void run(){
                            try{
                                for (int i = 210; i >=0; i--){
                                    Thread.sleep(i);
                                    pnSide.setSize(i,625);
                                }
                            }catch (Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }
                        }
                    };th.start();
                    x=0;
                    }
    }//GEN-LAST:event_lbl_appMouseClicked

    private void lbl_appblackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_appblackMouseClicked
       if (x == 0){
           pnSide.show();
           pnSide.setSize(x,625);
           Thread th = new Thread(){
               @Override
               public void run(){
                   try{
                       for (int i = 0; i <= x; i++){
                           Thread.sleep(i);
                           pnSide.setSize(i, 625);
                       }
                   }catch (Exception e){
                       JOptionPane.showMessageDialog(null,e);
                   }
               }
           };th.start();
           x=210;
       }
    }//GEN-LAST:event_lbl_appblackMouseClicked

    private void lbl_appMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_appMouseEntered
        labelcolor(lbl_app);
    }//GEN-LAST:event_lbl_appMouseEntered

    private void lbl_appMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_appMouseExited
        resetlabelcolor(lbl_app);
    }//GEN-LAST:event_lbl_appMouseExited

    private void lbl_HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HomeMousePressed
        // TODO add your handling code here:
        pnHome.setBackground(ClickedColor);
        pnProduksi.setBackground(DefaultColor);
        pnBarang.setBackground(DefaultColor);
        pnKaryawan.setBackground(DefaultColor);
        pnLaporan.setBackground(DefaultColor);
        
        MenuName.setText("Hi, There !");
    }//GEN-LAST:event_lbl_HomeMousePressed

    private void lbl_ProduksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ProduksiMousePressed
        // TODO add your handling code here:
        pnHome.setBackground(DefaultColor);
        pnProduksi.setBackground(ClickedColor);
        pnBarang.setBackground(DefaultColor);
        pnKaryawan.setBackground(DefaultColor);
        pnLaporan.setBackground(DefaultColor);
        
        MenuName.setText("I'ts Produksi Form");
    }//GEN-LAST:event_lbl_ProduksiMousePressed

    private void lbl_KaryawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KaryawanMousePressed
        // TODO add your handling code here:
        pnHome.setBackground(DefaultColor);
        pnProduksi.setBackground(DefaultColor);
        pnBarang.setBackground(DefaultColor);
        pnKaryawan.setBackground(ClickedColor);
        pnLaporan.setBackground(DefaultColor);
        
        MenuName.setText("It's Karyawan Form");
    }//GEN-LAST:event_lbl_KaryawanMousePressed

    private void lbl_LaporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LaporanMousePressed
        // TODO add your handling code here:
        pnHome.setBackground(DefaultColor);
        pnProduksi.setBackground(DefaultColor);
        pnBarang.setBackground(DefaultColor);
        pnKaryawan.setBackground(DefaultColor);
        pnLaporan.setBackground(ClickedColor);
        
        MenuName.setText("It's Laporan Form");
    }//GEN-LAST:event_lbl_LaporanMousePressed

    private void lbl_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HomeMouseClicked
        // TODO add your handling code here:
        Home  home = new Home();
        pnMain.removeAll();
        pnMain.add(home).setVisible(true);
        
    }//GEN-LAST:event_lbl_HomeMouseClicked

    private void lbl_ProduksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ProduksiMouseClicked
        // TODO add your handling code here:
        Produksi  produksi = new Produksi();
        pnMain.removeAll();
        pnMain.add(produksi).setVisible(true);
    }//GEN-LAST:event_lbl_ProduksiMouseClicked

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_KaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_KaryawanMouseClicked
        // TODO add your handling code here:
        Karyawan karyawan = new Karyawan();
        pnMain.removeAll();
        pnMain.add(karyawan).setVisible(true);
    }//GEN-LAST:event_lbl_KaryawanMouseClicked

    private void lbl_LaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_LaporanMouseClicked
        // TODO add your handling code here:
        Laporan  laporan = new Laporan();
        pnMain.removeAll();
        pnMain.add(laporan).setVisible(true);
    }//GEN-LAST:event_lbl_LaporanMouseClicked

    private void lbl_BarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BarangMouseClicked
        // TODO add your handling code here:
        Barang barang = new Barang();
        pnMain.removeAll();
        pnMain.add(barang).setVisible(true);
    }//GEN-LAST:event_lbl_BarangMouseClicked

    private void lbl_BarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BarangMousePressed
        // TODO add your handling code here:
        pnHome.setBackground(DefaultColor);
        pnProduksi.setBackground(DefaultColor);
        pnBarang.setBackground(ClickedColor);
        pnKaryawan.setBackground(DefaultColor);
        pnLaporan.setBackground(DefaultColor);
        
        MenuName.setText("It's Barang Form");
    }//GEN-LAST:event_lbl_BarangMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dasbor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dasbor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dasbor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dasbor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dasbor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Barang;
    private javax.swing.JLabel lbl_Home;
    private javax.swing.JLabel lbl_Karyawan;
    private javax.swing.JLabel lbl_Laporan;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_Produksi;
    private javax.swing.JLabel lbl_app;
    private javax.swing.JLabel lbl_appblack;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_icnBarang;
    private javax.swing.JLabel lbl_icnHome;
    private javax.swing.JLabel lbl_icnKaryawan;
    private javax.swing.JLabel lbl_icnLaporan;
    private javax.swing.JLabel lbl_icnProduksi;
    private javax.swing.JPanel pnBarang;
    private javax.swing.JPanel pnHome;
    private javax.swing.JPanel pnKaryawan;
    private javax.swing.JPanel pnLaporan;
    private javax.swing.JDesktopPane pnMain;
    private javax.swing.JPanel pnProduksi;
    private javax.swing.JPanel pnSide;
    private javax.swing.JPanel pnUp;
    // End of variables declaration//GEN-END:variables
    private void labelcolor(JLabel label){
        label.setBackground(new java.awt.Color(53,59,72));
    }
    private void resetlabelcolor(JLabel label){
        label.setBackground(new java.awt.Color(64,115,158));
    }
}
