/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nanda
 */
public class form_login extends javax.swing.JFrame {

    int xx, xy;
    
    /**
     * Creates new form form_login
     */
    public form_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlbg = new javax.swing.JPanel();
        button_exit = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        pct = new javax.swing.JLabel();
        pnlusn = new javax.swing.JPanel();
        usn = new javax.swing.JTextField();
        icnusn = new javax.swing.JLabel();
        pnlpw = new javax.swing.JPanel();
        pw = new javax.swing.JTextField();
        icnpw = new javax.swing.JLabel();
        login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlbg.setBackground(new java.awt.Color(255, 255, 255));
        pnlbg.setForeground(new java.awt.Color(0, 153, 255));

        button_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/rectangle-xmark.png"))); // NOI18N
        button_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_exitMouseClicked(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/logo.png"))); // NOI18N

        pct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/Consulting-bro (2).png"))); // NOI18N
        pct.setMaximumSize(new java.awt.Dimension(200, 200));

        pnlusn.setBackground(new java.awt.Color(72, 126, 176));

        usn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usn.setText("Username");
        usn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 2));
        usn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usnFocusLost(evt);
            }
        });

        icnusn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/user (2).png"))); // NOI18N

        javax.swing.GroupLayout pnlusnLayout = new javax.swing.GroupLayout(pnlusn);
        pnlusn.setLayout(pnlusnLayout);
        pnlusnLayout.setHorizontalGroup(
            pnlusnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlusnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icnusn)
                .addGap(18, 18, 18)
                .addComponent(usn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlusnLayout.setVerticalGroup(
            pnlusnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlusnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(usn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(icnusn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlpw.setBackground(new java.awt.Color(72, 126, 176));

        pw.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pw.setText("Password");
        pw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 2));
        pw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwFocusLost(evt);
            }
        });

        icnpw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/lock.png"))); // NOI18N

        javax.swing.GroupLayout pnlpwLayout = new javax.swing.GroupLayout(pnlpw);
        pnlpw.setLayout(pnlpwLayout);
        pnlpwLayout.setHorizontalGroup(
            pnlpwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpwLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icnpw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(pw, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlpwLayout.setVerticalGroup(
            pnlpwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpwLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlpwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icnpw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        login.setBackground(new java.awt.Color(72, 126, 176));
        login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");

        javax.swing.GroupLayout pnlbgLayout = new javax.swing.GroupLayout(pnlbg);
        pnlbg.setLayout(pnlbgLayout);
        pnlbgLayout.setHorizontalGroup(
            pnlbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbgLayout.createSequentialGroup()
                .addContainerGap(616, Short.MAX_VALUE)
                .addComponent(button_exit)
                .addGap(10, 10, 10))
            .addGroup(pnlbgLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(pct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlbgLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pnlbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlpw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlusn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlbgLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlbgLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        pnlbgLayout.setVerticalGroup(
            pnlbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_exit)
                .addGap(15, 15, 15)
                .addGroup(pnlbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlbgLayout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlusn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlpw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(login))
                    .addComponent(pct, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(428, 428, 428))
        );

        getContentPane().add(pnlbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
      xx = evt.getX();
      xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void button_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_exitMouseClicked
        dispose();
    }//GEN-LAST:event_button_exitMouseClicked

    private void usnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usnFocusGained
       String usser= usn.getText();
       if(usser.equals("Username")){
           usn.setText("");
       }
    }//GEN-LAST:event_usnFocusGained

    private void pwFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwFocusGained
       String pass=pw.getText();
       if(pass.equals("Password")){
           pw.setText("");
       }
    }//GEN-LAST:event_pwFocusGained

    private void usnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usnFocusLost
      String usser=usn.getText();
      if(usser.equals("")||usser.equals("Username")){
          usn.setText("Username");
      }
    }//GEN-LAST:event_usnFocusLost

    private void pwFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwFocusLost
         String pass=pw.getText();
      if(pass.equals("")||pass.equals("Password")){
          pw.setText("Password");
      }
    }//GEN-LAST:event_pwFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel button_exit;
    private javax.swing.JLabel icnpw;
    private javax.swing.JLabel icnusn;
    private javax.swing.JButton login;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel pct;
    private javax.swing.JPanel pnlbg;
    private javax.swing.JPanel pnlpw;
    private javax.swing.JPanel pnlusn;
    private javax.swing.JTextField pw;
    private javax.swing.JTextField usn;
    // End of variables declaration//GEN-END:variables
}
