/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author nanda
 */
public class Dasbor extends javax.swing.JFrame {

    /**
     * Creates new form Dasbor
     */
    
    Color DefaultColor, ClickedColor;
    
    public Dasbor() {
        initComponents();
        DefaultColor = new Color(64,115,158);
        ClickedColor = new Color(53,59,72);
        
        //Set default color to pan on run time
        
        pnMaster.setBackground(DefaultColor);
        pnHome.setBackground(DefaultColor);
        pnTransaction.setBackground(DefaultColor);
        pnReport.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnSide = new javax.swing.JPanel();
        lbl_app = new javax.swing.JLabel();
        pnHome = new javax.swing.JPanel();
        lbl_icnHome1 = new javax.swing.JLabel();
        lbl_Home1 = new javax.swing.JLabel();
        pnMaster = new javax.swing.JPanel();
        lbl_icnMaster = new javax.swing.JLabel();
        lbl_Master = new javax.swing.JLabel();
        pnTransaction = new javax.swing.JPanel();
        lbl_icnTransaction = new javax.swing.JLabel();
        lbl_Transaction = new javax.swing.JLabel();
        pnReport = new javax.swing.JPanel();
        lbl_icnReport = new javax.swing.JLabel();
        lbl_Report = new javax.swing.JLabel();
        pnMain = new javax.swing.JDesktopPane();
        pnUp = new javax.swing.JPanel();
        lbl_appblack = new javax.swing.JLabel();
        lbl_Logo = new javax.swing.JLabel();
        MenuName = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 625));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 552));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnSide.setBackground(new java.awt.Color(64, 115, 158));
        pnSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_app.setBackground(new java.awt.Color(64, 115, 158));
        lbl_app.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_app.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/apps.png"))); // NOI18N
        lbl_app.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_app.setOpaque(true);
        lbl_app.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_appMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_appMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_appMouseExited(evt);
            }
        });
        pnSide.add(lbl_app, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 40, 40));

        pnHome.setBackground(new java.awt.Color(64, 115, 158));
        pnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icnHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_icnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/home.png"))); // NOI18N
        pnHome.add(lbl_icnHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 40, 30));

        lbl_Home1.setBackground(new java.awt.Color(64, 115, 158));
        lbl_Home1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Home1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Home1.setText("Home");
        lbl_Home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Home1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_Home1MousePressed(evt);
            }
        });
        pnHome.add(lbl_Home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 20));

        pnSide.add(pnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 40));

        pnMaster.setBackground(new java.awt.Color(64, 115, 158));
        pnMaster.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icnMaster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_icnMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/van-fast.png"))); // NOI18N
        pnMaster.add(lbl_icnMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 40, 30));

        lbl_Master.setBackground(new java.awt.Color(64, 115, 158));
        lbl_Master.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Master.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Master.setText("Master");
        lbl_Master.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_MasterMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_MasterMousePressed(evt);
            }
        });
        pnMaster.add(lbl_Master, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 20));

        pnSide.add(pnMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 40));

        pnTransaction.setBackground(new java.awt.Color(64, 115, 158));
        pnTransaction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icnTransaction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_icnTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/sack-dollar.png"))); // NOI18N
        pnTransaction.add(lbl_icnTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 40, 30));

        lbl_Transaction.setBackground(new java.awt.Color(64, 115, 158));
        lbl_Transaction.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Transaction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Transaction.setText("Transaction");
        lbl_Transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_TransactionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_TransactionMousePressed(evt);
            }
        });
        pnTransaction.add(lbl_Transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 20));

        pnSide.add(pnTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 40));

        pnReport.setBackground(new java.awt.Color(64, 115, 158));
        pnReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_icnReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_icnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/light-emergency-on.png"))); // NOI18N
        pnReport.add(lbl_icnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 40, 30));

        lbl_Report.setBackground(new java.awt.Color(64, 115, 158));
        lbl_Report.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lbl_Report.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Report.setText("Report");
        lbl_Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ReportMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_ReportMousePressed(evt);
            }
        });
        pnReport.add(lbl_Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 20));

        pnSide.add(pnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 210, 40));

        jPanel1.add(pnSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, -1, 552));

        pnMain.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        jPanel1.add(pnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 73, 790, 625));

        pnUp.setBackground(new java.awt.Color(72, 126, 176));
        pnUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_appblack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_appblack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/apps (1).png"))); // NOI18N
        lbl_appblack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_appblack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_appblackMouseClicked(evt);
            }
        });
        pnUp.add(lbl_appblack, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 83, 40, 40));

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/logo-removebg-preview.png"))); // NOI18N
        lbl_Logo.setText("jLabel2");
        pnUp.add(lbl_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 73, 240, 130));

        MenuName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        MenuName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/user.png"))); // NOI18N
        MenuName.setText(" Hi, Mrs. !");
        pnUp.add(MenuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 210, 70));

        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_icon/rectangle-xmark.png"))); // NOI18N
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });
        pnUp.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, 30));

        jPanel1.add(pnUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int x = 210;
    private void lbl_appMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_appMouseClicked
        if (x == 210){
            pnSide.setSize(210,625);
            Thread th= new Thread()
                    {@Override
                        public void run(){
                            try{
                                for (int i = 210; i >=0; i--){
                                    Thread.sleep(i);
                                    pnSide.setSize(i,625);
                                }
                            }catch (Exception e){
                                JOptionPane.showMessageDialog(null, e);
                            }
                        }
                    };th.start();
                    x=0;
                    }
    }//GEN-LAST:event_lbl_appMouseClicked

    private void lbl_appblackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_appblackMouseClicked
       if (x == 0){
           pnSide.show();
           pnSide.setSize(x,625);
           Thread th = new Thread(){
               @Override
               public void run(){
                   try{
                       for (int i = 0; i <= x; i++){
                           Thread.sleep(i);
                           pnSide.setSize(i, 625);
                       }
                   }catch (Exception e){
                       JOptionPane.showMessageDialog(null,e);
                   }
               }
           };th.start();
           x=210;
       }
    }//GEN-LAST:event_lbl_appblackMouseClicked

    private void lbl_appMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_appMouseEntered
        labelcolor(lbl_app);
    }//GEN-LAST:event_lbl_appMouseEntered

    private void lbl_appMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_appMouseExited
        resetlabelcolor(lbl_app);
    }//GEN-LAST:event_lbl_appMouseExited

    private void lbl_Home1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Home1MousePressed
        // TODO add your handling code here:
        pnHome.setBackground(ClickedColor);
        pnMaster.setBackground(DefaultColor);
        pnTransaction.setBackground(DefaultColor);
        pnReport.setBackground(DefaultColor);
        
        MenuName.setText("Hi, There !");
    }//GEN-LAST:event_lbl_Home1MousePressed

    private void lbl_MasterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MasterMousePressed
        // TODO add your handling code here:
        pnHome.setBackground(DefaultColor);
        pnMaster.setBackground(ClickedColor);
        pnTransaction.setBackground(DefaultColor);
        pnReport.setBackground(DefaultColor);
        
        MenuName.setText("I'ts Master Form");
    }//GEN-LAST:event_lbl_MasterMousePressed

    private void lbl_TransactionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TransactionMousePressed
        // TODO add your handling code here:
        pnMaster.setBackground(DefaultColor);
        pnHome.setBackground(DefaultColor);
        pnTransaction.setBackground(ClickedColor);
        pnReport.setBackground(DefaultColor);
        
        MenuName.setText("It's Transaction Form");
    }//GEN-LAST:event_lbl_TransactionMousePressed

    private void lbl_ReportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ReportMousePressed
        // TODO add your handling code here:
        pnMaster.setBackground(DefaultColor);
        pnHome.setBackground(DefaultColor);
        pnTransaction.setBackground(DefaultColor);
        pnReport.setBackground(ClickedColor);
        
        MenuName.setText("It's Report Form");
    }//GEN-LAST:event_lbl_ReportMousePressed

    private void lbl_Home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Home1MouseClicked
        // TODO add your handling code here:
        Home  home = new Home();
        pnMain.removeAll();
        pnMain.add(home).setVisible(true);
        
    }//GEN-LAST:event_lbl_Home1MouseClicked

    private void lbl_MasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MasterMouseClicked
        // TODO add your handling code here:
        Master  master = new Master();
        pnMain.removeAll();
        pnMain.add(master).setVisible(true);
    }//GEN-LAST:event_lbl_MasterMouseClicked

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_TransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TransactionMouseClicked
        // TODO add your handling code here:
        Transaction  transaction = new Transaction();
        pnMain.removeAll();
        pnMain.add(transaction).setVisible(true);
    }//GEN-LAST:event_lbl_TransactionMouseClicked

    private void lbl_ReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ReportMouseClicked
        // TODO add your handling code here:
        Report  report = new Report();
        pnMain.removeAll();
        pnMain.add(report).setVisible(true);
    }//GEN-LAST:event_lbl_ReportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dasbor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dasbor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dasbor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dasbor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dasbor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Home1;
    private javax.swing.JLabel lbl_Logo;
    private javax.swing.JLabel lbl_Master;
    private javax.swing.JLabel lbl_Report;
    private javax.swing.JLabel lbl_Transaction;
    private javax.swing.JLabel lbl_app;
    private javax.swing.JLabel lbl_appblack;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_icnHome1;
    private javax.swing.JLabel lbl_icnMaster;
    private javax.swing.JLabel lbl_icnReport;
    private javax.swing.JLabel lbl_icnTransaction;
    private javax.swing.JPanel pnHome;
    private javax.swing.JDesktopPane pnMain;
    private javax.swing.JPanel pnMaster;
    private javax.swing.JPanel pnReport;
    private javax.swing.JPanel pnSide;
    private javax.swing.JPanel pnTransaction;
    private javax.swing.JPanel pnUp;
    // End of variables declaration//GEN-END:variables
    private void labelcolor(JLabel label){
        label.setBackground(new java.awt.Color(53,59,72));
    }
    private void resetlabelcolor(JLabel label){
        label.setBackground(new java.awt.Color(64,115,158));
    }
}
